#!/usr/bin/env python3
"""
AppQuanta App Preview Generator
Creates a basic Flutter app structure based on user specifications
"""

import os
import json
from datetime import datetime
from typing import Dict, List, Optional

class AppPreviewGenerator:
    def __init__(self, app_data: Dict):
        self.app_data = app_data
        self.app_name = app_data.get('name', 'MyApp').replace(' ', '_')
        self.description = app_data.get('description', '')
        self.icon = app_data.get('icon', 'app')
        self.color = app_data.get('color', '#4E9FFF')
        self.screens = app_data.get('screens', ['Home', 'About'])
        self.status = app_data.get('status', 'active')

    def generate_app_structure(self) -> str:
        """Generate the basic Flutter app structure"""
        app_dir = f"preview_{self.app_name.lower()}"

        if not os.path.exists(app_dir):
            os.makedirs(app_dir)

        # Generate pubspec.yaml
        pubspec_content = self._generate_pubspec()
        with open(f"{app_dir}/pubspec.yaml", 'w') as f:
            f.write(pubspec_content)

        # Generate main.dart
        main_content = self._generate_main_dart()
        with open(f"{app_dir}/lib/main.dart", 'w') as f:
            f.write(main_content)

        # Generate screens
        self._generate_screens(app_dir)

        # Generate README
        readme_content = self._generate_readme()
        with open(f"{app_dir}/README.md", 'w') as f:
            f.write(readme_content)

        return app_dir

    def _generate_pubspec(self) -> str:
        return f'''name: {self.app_name.lower()}
description: {self.description}
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
'''

    def _generate_main_dart(self) -> str:
        screens_imports = '\n'.join([f"import 'screens/{screen.lower()}_screen.dart';" for screen in self.screens])

        routes = '\n'.join([f"        '/{screen.lower()}': (context) => {screen}Screen()," for screen in self.screens])

        return f'''import 'package:flutter/material.dart';
{screens_imports}

void main() {{
  runApp(const MyApp());
}}

class MyApp extends StatelessWidget {{
  const MyApp({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: '{self.app_data.get("name", "My App")}',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Color({self._hex_to_color(self.color)})),
        useMaterial3: true,
      ),
      initialRoute: '/{self.screens[0].lower()}',
      routes: {{
{routes}
      }},
    );
  }}
}}
'''

    def _generate_screens(self, app_dir: str):
        screens_dir = f"{app_dir}/lib/screens"
        if not os.path.exists(screens_dir):
            os.makedirs(screens_dir)

        for screen in self.screens:
            screen_content = self._generate_screen_class(screen)
            with open(f"{screens_dir}/{screen.lower()}_screen.dart", 'w') as f:
                f.write(screen_content)

    def _generate_screen_class(self, screen_name: str) -> str:
        return f'''import 'package:flutter/material.dart';

class {screen_name}Screen extends StatelessWidget {{
  const {screen_name}Screen({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(
        title: const Text('{screen_name}'),
        backgroundColor: Color({self._hex_to_color(self.color)}),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.{self._get_icon_for_screen(screen_name)},
              size: 80,
              color: Color({self._hex_to_color(self.color)}),
            ),
            const SizedBox(height: 20),
            Text(
              '{screen_name}',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            const SizedBox(height: 10),
            Text(
              'Welcome to {screen_name} screen',
              style: Theme.of(context).textTheme.bodyLarge,
            ),
          ],
        ),
      ),
    );
  }}
}}
'''

    def _generate_readme(self) -> str:
        return f'''# {self.app_data.get('name', 'My App')}

{self.description}

## Generated App Preview

This is a preview of your app generated by AppQuanta.

### Features
- **Name**: {self.app_data.get('name', 'My App')}
- **Status**: {self.status}
- **Screens**: {', '.join(self.screens)}
- **Theme Color**: {self.color}

### Screens Included
{chr(10).join([f"- {screen}" for screen in self.screens])}

### How to Run
1. Make sure you have Flutter installed
2. Run `flutter pub get` in this directory
3. Run `flutter run` to start the app

### Generated by AppQuanta
Created on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
'''

    def _hex_to_color(self, hex_color: str) -> str:
        """Convert hex color to Flutter Color int"""
        hex_color = hex_color.lstrip('#')
        if len(hex_color) == 6:
            hex_color = 'FF' + hex_color
        return f"0x{hex_color.upper()}"

    def _get_icon_for_screen(self, screen_name: str) -> str:
        """Get appropriate icon for screen type"""
        icon_map = {
            'Home': 'home',
            'About': 'info',
            'Contact': 'contact_mail',
            'Gallery': 'photo_library',
            'Settings': 'settings',
            'Profile': 'person',
        }
        return icon_map.get(screen_name, 'star')

def create_app_preview(app_data: Dict) -> str:
    """Create a preview app from app data"""
    generator = AppPreviewGenerator(app_data)
    app_dir = generator.generate_app_structure()

    print(f"✅ App preview created in: {app_dir}")
    print(f"📱 App Name: {app_data.get('name', 'My App')}")
    print(f"🎨 Theme Color: {app_data.get('color', '#4E9FFF')}")
    print(f"📄 Screens: {', '.join(app_data.get('screens', []))}")

    return app_dir

if __name__ == "__main__":
    # Example usage
    sample_app = {
        "name": "Meu App Incrível",
        "description": "Um app incrível criado com AppQuanta",
        "icon": "app",
        "color": "#4E9FFF",
        "screens": ["Home", "About", "Contact"],
        "status": "active"
    }

    create_app_preview(sample_app)
